#!/bin/bash

build() {
  add_file /etc/consolecolors && add_binary /usr/bin/setvtrgb && add_runscript
}

help() {
  cat <<HELPEOF
This hooks will setup console colors during early user space.
HELPEOF
}
