return require('dotfiles.autoload')('dotfiles.lsp', {
  basic_handlers = ..., ---@module 'basic_handlers'
  custom_ui = ..., ---@module 'custom_ui'
  diagnostics = ..., ---@module 'diagnostics'
  diagnostics_old = ..., ---@module 'diagnostics_old'
  dummy_entry_plug = ..., ---@module 'dummy_entry_plug'
  float = ..., ---@module 'float'
  global_settings = ..., ---@module 'global_settings'
  highlight_match = ..., ---@module 'highlight_match'
  hover = ..., ---@module 'hover'
  ignition = ..., ---@module 'ignition'
  markup = ..., ---@module 'markup'
  nvim_lua_dev = ..., ---@module 'nvim_lua_dev'
  progress = ..., ---@module 'progress'
  signature_help = ..., ---@module 'signature_help'
  symbols = ..., ---@module 'symbols'
  unified_settings_repository = ..., ---@module 'unified_settings_repository'
  utils = ..., ---@module 'utils'
})
