#!/usr/bin/env python
import sys
import os.path

sys.path.insert(1, os.path.join(os.path.dirname(__file__), "..", "script-resources"))

from pycalc_startup import *

exec(compile(" ".join(sys.argv[1:]), "<string>", "single"))
