#!/usr/bin/env sh
set -euo pipefail

if package="$(set -euo pipefail; {

  expac --sync '%r/%a/%n %v - %d'
  curl --silent --location --fail --max-time 10 'https://aur.archlinux.org/packages.gz' |
    gzip -d | awk '!/^#/ { print "aur/" $0 }'

} | rofi -dmenu)" && [ -n "$package" ]; then

  package="${package%% *}"
  case "$package" in
    (aur/*) url="https://aur.archlinux.org/packages/${package#aur/}/";;
    (*)     url="https://www.archlinux.org/packages/${package}/";;
  esac

  xdg-open "$url"
fi
