#!/usr/bin/env bash

declare -A faces=(
  ["shrug face"]='¯\_(ツ)_/¯'
  ["shrug face (markdown)"]='¯\\\_(ツ)\_/¯'
  ["lenny face"]='( ͡° ͜ʖ ͡°)'
  ["table flip"]='(ノಠ益ಠ)ノ彡┻━┻'
)

if face_name="$(printf '%s\n' "${!faces[@]}" | rofi -dmenu -i)"; then
  face="${faces[$face_name]}"
  echo -n "$face" | xsel --clipboard --input
  notify-send --icon=utilities-terminal --expire-time=2500 "$0" "$face_name copied to clipboard"
fi
