#!/usr/bin/env python3

# <https://discord.com/developers/docs/resources/user#user-object>
# <https://discord.com/developers/docs/resources/user#user-object#get-user>
# <https://discord.com/developers/docs/reference>

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request

DISCORD_EPOCH = 1420070400000  # milliseconds
# https://discord.com/developers/docs/resources/user#user-object-user-flags
DISCORD_FLAGS = {
  "Discord Employee": 1 << 0,
  "Discord Partner": 1 << 1,
  "HypeSquad Events": 1 << 2,
  "Bug Hunter Level 1": 1 << 3,
  "House of Bravery": 1 << 6,
  "House of Brilliance": 1 << 7,
  "House of Balance": 1 << 8,
  "Early Supporter": 1 << 9,
  "Team User": 1 << 10,
  "System": 1 << 12,
  "Bug Hunter Level 2": 1 << 14,
  "Verified Bot": 1 << 16,
  "Verified Bot Developer": 1 << 17,
}

parser = argparse.ArgumentParser()
parser.add_argument("user_snowflake", type=int)
parser.add_argument("--bot-token", type=str)
parser.add_argument("--image-size", type=int)
parser.add_argument("--get-prop", type=str)
parser.add_argument("--api-response", action="store_true")
cli_args = parser.parse_args()

user_snowflake: int = cli_args.user_snowflake

bot_token: "str | None" = cli_args.bot_token
if bot_token is None:
  with open(os.path.expanduser("~/.config/dotfiles/discord-tools-bot-token.txt")) as f:
    bot_token = f.read().strip()

image_size: "int | None" = cli_args.image_size
if not (image_size is None or (image_size > 0 and image_size & (image_size - 1)) == 0):
  parser.error("image_size must be greater than zero and a power of two")

try:
  opener = urllib.request.build_opener()
  # Don't send the User-Agent header, Discord blocks the default one
  opener.addheaders = []
  with opener.open(
    urllib.request.Request(
      f"http://discord.com/api/users/{user_snowflake}",
      headers={"Authorization": f"Bot {bot_token}"},
    ),
    timeout=10,
  ) as response:
    raw_data = json.load(response)
except urllib.error.HTTPError as err:
  print(err, file=sys.stderr)
  print(err.read(), file=sys.stderr)
  raise err

if cli_args.api_response:
  json.dump(raw_data, sys.stdout, ensure_ascii=False, indent=2)
  sys.stdout.write("\n")
  sys.exit()

data: "dict[str, str | bool]" = {}

data["ID"] = raw_data["id"]
data["Name"] = f"{raw_data['username']}#{raw_data['discriminator']}"

default_avatar_url = (
  f"https://cdn.discordapp.com/embed/avatars/{int(raw_data['discriminator'], 10) % 5}.png"
)

if raw_data["avatar"] is not None:
  ext = "gif" if raw_data["avatar"].startswith("a_") else "png"
  avatar_url = f"https://cdn.discordapp.com/avatars/{raw_data['id']}/{raw_data['avatar']}.{ext}"
else:
  avatar_url = default_avatar_url

if image_size is not None:
  avatar_url += f"?size={image_size}"

data["Avatar"] = avatar_url
data["Default avatar"] = default_avatar_url

data["Bot"] = raw_data.get("bot", False)
data["System user"] = raw_data.get("system", False)

# https://discord.com/developers/docs/reference#convert-snowflake-to-datetime
snowflake_creation_time = (user_snowflake >> 22) + DISCORD_EPOCH
data["Created at"] = (
  f"{time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(snowflake_creation_time // 1000))}."
  f"{snowflake_creation_time % 1000} UTC"
)

user_flags = raw_data["public_flags"]
data["Flags"] = (
  ", ".join(flag for flag, bitmask in DISCORD_FLAGS.items() if user_flags & bitmask)
  if user_flags != 0
  else "<none>"
)

if cli_args.get_prop is None:
  max_name_length = max(map(len, data.keys()))
  for name, value in data.items():
    if value is True:
      value = "yes"
    elif value is False:
      value = "no"
    print(f"\x1b[1m{name:>{max_name_length + 1}}:\x1b[0m {value}")
else:
  print(data[cli_args.get_prop])
