#!/usr/bin/env python3

import os
import sys

import discord

guild_id = int(sys.argv[1])
voice_channel_id = int(sys.argv[2])
pulseaudio_device = sys.argv[3]

with open(os.path.expanduser("~/.config/dotfiles/discord-tools-bot-token.txt")) as f:
  bot_token = f.read().strip()

bot = discord.Client()


@bot.event
async def on_ready() -> None:
  assert bot.user
  print(f"logged in as {bot.user} ({bot.user.id})")

  guild = bot.get_guild(guild_id)
  if guild is None:
    raise Exception("guild not found")

  voice_channel = guild.get_channel(voice_channel_id)
  if voice_channel is None:
    raise Exception("channel not found")
  if not isinstance(voice_channel, discord.VoiceChannel):
    raise Exception("not a voice channel")

  voice_client = await voice_channel.connect()
  print(f"connected to {voice_channel} ({voice_channel.id}) in {guild} ({guild.id})")

  source = discord.FFmpegPCMAudio(pulseaudio_device, before_options="-f pulse")
  voice_client.play(source, after=lambda e: print("Player error: %s" % e) if e else None)


bot.run(bot_token)
