#!/usr/bin/env python3

# https://discord.com/developers/docs/reference#snowflakes

import sys
import time

DISCORD_EPOCH = 1420070400000  # milliseconds

user_snowflake = int(sys.argv[1])

timestamp = (user_snowflake >> 22) + DISCORD_EPOCH
internal_worker_id = (user_snowflake >> 17) & 0x1F
internal_process_id = (user_snowflake >> 12) & 0x1F
increment = user_snowflake & 0xFFF

for field, value in [
  (
    "Created at",
    f"{time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(timestamp // 1000))}.{timestamp % 1000}",
  ),
  ("Internal worker ID", internal_worker_id),
  ("Internal process ID", internal_process_id),
  ("Increment", increment),
]:
  print(f"\x1b[1m{field:>21}:\x1b[0m {value}")
