#!/usr/bin/env python3

import json
import sys

from dotfiles import factorio

if __name__ == "__main__":
  data = factorio.load_blueprint_string(sys.stdin.buffer.read())
  json.dump(data, sys.stdout, ensure_ascii=False, indent=2)
