#!/usr/bin/env python3

import json
import sys

from dotfiles import factorio

if __name__ == "__main__":
  print(
    json.dumps(
      factorio.load_blueprint_string(sys.stdin.buffer.read()),
      ensure_ascii=False,
      indent=2,
    )
  )
