#!/usr/bin/env python3
# <https://wiki.factorio.com/Mod_settings_file_format>
# <https://forums.factorio.com/59851>
# <https://www.dropbox.com/sh/uscmj9y3cjfwpsr/AAD35_ZZu64EBi0awLA07fxga?dl=0>
# <https://github.com/credomane/factoriomodsettings/blob/master/src/FactorioModSettings.js>

import json
import os
import sys

from dotfiles import factorio

if __name__ == "__main__":
  if len(sys.argv) >= 2:
    settings_path = sys.argv[1]
  else:
    settings_path = os.path.expanduser("~/.factorio/mods/mod-settings.dat")

  with open(settings_path, "rb") as f:
    version = factorio.read_factorio_version(f)

    always_false_flag = factorio.read_bool(f)
    if always_false_flag:
      raise Exception("the always-False-flag is True for some reason")

    deserialized_data = {
      "factorio_version": version._asdict(),
      "data": factorio.read_property_tree(f),
    }

    print(json.dumps(deserialized_data, indent=2, ensure_ascii=False))
