#!/usr/bin/env sh
set -eu

for cmd in diff-so-fancy diff-highlight; do
  if command -v "$cmd" >/dev/null 2>&1; then
    exec "$cmd" "$@"
  fi
done

try_contrib_dir() {
  local contrib="$1"
  if [ -d "${contrib}/diff-highlight" ]; then
    script="${contrib}/diff-highlight/diff-highlight"
    if [ -x "$script" ]; then
      exec "$script"
    elif [ -r "$script" ] && command -v perl >/dev/null 2>&1; then
      exec perl "$script"
    fi
  fi
}

try_prefix() {
  local prefix="$1"
  if [ -d "$prefix" ]; then
    try_contrib_dir "${prefix}/git"               # Arch Linux
    try_contrib_dir "${prefix}/git/contrib"       # NixOS
    try_contrib_dir "${prefix}/doc/git/contrib"   # Debian/Ubuntu
    try_contrib_dir "${prefix}/git-core/contrib"  # Homebrew on macOS
  fi
}

if git_exe="$(command -v git 2>/dev/null)"; then
  # `readlink -f` seems to be more portable than `realpath`.
  # <https://unix.stackexchange.com/questions/136494/whats-the-difference-between-realpath-and-readlink-f>
  git_exe="$(readlink -f "$git_exe")"
  git_bin_dir="$(dirname "$git_exe")"
  try_prefix "${git_bin_dir}/../share"     # when `git` resolves to `$prefix/bin/git`
  try_prefix "${git_bin_dir}/../../share"  # when `git` resolves to `$prefix/libexec/git-core/git`
fi

# Try some well-known paths if the above didn't work.
try_prefix "/usr/local/share"
try_prefix "/usr/share"

# Just pass the input through unchanged as a last effort.
exec cat -
